#####################################################################################
# Wayland Clipboard Integration
#####################################################################################
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy && wl-paste -n | wl-copy -p"
bind-key p run "wl-paste -n | tmux load-buffer - ; tmux paste-buffer"

#####################################################################################
# Keybinds
#####################################################################################

# LEADER
set -g prefix C-s

# Reload configuration
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Windows
bind -n S-down new-window               # Shift + ArrowDown = New Window
bind -n S-left prev                     # Shift + ArrowLeft = Previous Window
bind -n S-right next                    # Shift + ArrowRight = Next Window
bind -n C-left swap-window -t -1        # Ctrl + ArrowLeft = Swap Window to [Left]
bind -n C-right swap-window -t +1       # Ctrl + ArrowRight = Swap Window to [Right]

# Split Panes
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Pane Selecction
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Layout Selection
bind -n M-1 select-layout even-horizontal
bind -n M-2 select-layout even-vertical
bind -n M-3 select-layout main-horizontal
bind -n M-4 select-layout main-vertical
bind -n M-5 select-layout tiled

# Monitoring
setw -g monitor-activity on
set -g visual-activity on

# Misc
set -g mouse on
setw -g mode-keys vi

#####################################################################################
# TPM
#####################################################################################

set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavor 'macchiato'
set -g @catppuccin_status_background "none"

set -g @plugin 'ofirgall/tmux-window-name'
set -g @plugin 'alexwforsythe/tmux-which-key'

run '/usr/share/tmux-plugin-manager/tpm'

