$background = rgb(0F0010)
$foreground = rgb(E1B5EA)
$color0 = rgb(332335)
$color1 = rgb(66A54F)
$color2 = rgb(1E8A41)
$color3 = rgb(4F8A20)
$color4 = rgb(598268)
$color5 = rgb(45663E)
$color6 = rgb(39C31E)
$color7 = rgb(CC8CD9)
$color8 = rgb(8F6298)
$color9 = rgb(66A54F)
$color10 = rgb(1E8A41)
$color11 = rgb(4F8A20)
$color12 = rgb(598268)
$color13 = rgb(45663E)
$color14 = rgb(39C31E)
$color15 = rgb(CC8CD9)