-- ╔══════════════════════════════════════════════╗
-- ║              Theme / Colors                 ║
-- ╚══════════════════════════════════════════════╝
-- Generated by wallust

BACKGROUND = "rgb({{background | strip}})"
FOREGROUND = "rgb({{foreground | strip}})"
COLOR0 = "rgb({{color0 | strip}})"
COLOR1 = "rgb({{color1 | strip}})"
COLOR2 = "rgb({{color2 | strip}})"
COLOR3 = "rgb({{color3 | strip}})"
COLOR4 = "rgb({{color4 | strip}})"
COLOR5 = "rgb({{color5 | strip}})"
COLOR6 = "rgb({{color6 | strip}})"
COLOR7 = "rgb({{color7 | strip}})"
COLOR8 = "rgb({{color8 | strip}})"
COLOR9 = "rgb({{color9 | strip}})"
COLOR10 = "rgb({{color10 | strip}})"
COLOR11 = "rgb({{color11 | strip}})"
COLOR12 = "rgb({{color12 | strip}})"
COLOR13 = "rgb({{color13 | strip}})"
COLOR14 = "rgb({{color14 | strip}})"
COLOR15 = "rgb({{color15 | strip}})"
