context.modules = [
      { name = libpipewire-module-loopback
      args = {
          node.description = "Game"
          capture.props = {
              node.name = "sink_game"
              media.class = "Audio/Sink"
          }
          playback.props = {
              node.name = "playback_game"
              target.object = "auto"
          }
      }
    },
    { name = libpipewire-module-loopback
      args = {
          node.description = "Chat"
          capture.props = {
              node.name = "sink_chat"
              media.class = "Audio/Sink"
          }
          playback.props = {
              node.name = "playback_chat"
              target.object = "auto"
          }
      }
    },
    { name = libpipewire-module-loopback
      args = {
          node.description = "Media"
          capture.props = {
              node.name = "sink_media"
              media.class = "Audio/Sink"
          }
          playback.props = {
              node.name = "playback_media"
              target.object = "auto"
          }
      }
    },
    { name = libpipewire-module-loopback
      args = {
          node.description = "Aux"
          capture.props = {
              node.name = "sink_aux"
              media.class = "Audio/Sink"
          }
          playback.props = {
              node.name = "playback_aux"
              target.object = "auto"
          }
      }
    },
]