context.modules = [
      { name = libpipewire-module-loopback
      args = {
          node.description = "General"
          capture.props = {
              node.name = "sink_general"
              media.class = "Audio/Sink"
          }
          playback.props = {
              node.name = "playback_general"
              target.object = "auto"
          }
      }
    },
    { name = libpipewire-module-loopback
      args = {
          node.description = "Game"
          capture.props = {
              node.name = "sink_games"
              media.class = "Audio/Sink"
          }
          playback.props = {
              node.name = "playback_games"
              target.object = "auto"
          }
      }
    },
    { name = libpipewire-module-loopback
      args = {
          node.description = "Music"
          capture.props = {
              node.name = "sink_music"
              media.class = "Audio/Sink"
          }
          playback.props = {
              node.name = "playback_music"
              target.object = "auto"
          }
      }
    },
    { name = libpipewire-module-loopback
      args = {
          node.description = "Multimedia"
          capture.props = {
              node.name = "sink_multimedia"
              media.class = "Audio/Sink"
          }
          playback.props = {
              node.name = "playback_multimedia"
              target.object = "auto"
          }
      }
    },
    { name = libpipewire-module-loopback
      args = {
          node.description = "Aux"
          capture.props = {
              node.name = "sink_aux"
              media.class = "Audio/Sink"
          }
          playback.props = {
              node.name = "playback_aux"
              target.object = "auto"
          }
      }
    },
]