$background = rgb(190000)
$foreground = rgb(C0C4C3)
$color0 = rgb(2F1A1A)
$color1 = rgb(C35A64)
$color2 = rgb(D07666)
$color3 = rgb(818586)
$color4 = rgb(927167)
$color5 = rgb(4D4C4F)
$color6 = rgb(737C7B)
$color7 = rgb(9CA2A1)