$background = rgb(190000)
$foreground = rgb(D0D3D1)
$color0 = rgb(2E1412)
$color1 = rgb(EC6C66)
$color2 = rgb(5DB08D)
$color3 = rgb(927366)
$color4 = rgb(6A737A)
$color5 = rgb(63564F)
$color6 = rgb(79807C)
$color7 = rgb(B4B7B5)