$terminal = kitty
$mod = SUPER
$browser = microsoft-edge-stable
$menu = wofi --show drun
$bluetooth-manager = overskride

source = ~/.config/hypr/themes/wallust.conf
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/input.conf

exec-once = gnome-keyring-daemon --start --components=pkcs11,secrets,ssh
exec-once = swww-daemon
exec-once = swaync