source = ~/.config/hypr/themes/wallust.conf

background = $background
base = $color0
text = $foreground
alternate_base = $color3
bright_text = $color7

accent = $color2
accent_secondary = $color4

h1_size = 15
h2_size = 13
h3_size = 11
font_size = 10
small_font_size = 9

rounding_large = 10
rounding_small = 5