$terminal = kitty
$mod = SUPER
$browser = microsoft-edge-stable
$menu = wofi --show drun --insensitive --allow-images --no-actions
$bluetooth-manager = kitty -e bluetui
$power-menu = ~/.local/bin/power-menu
$screenshot = ~/.local/bin/hyprshot

source = ~/.config/hypr/themes/wallust.conf
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/rules.conf

source = ~/.config/hypr/plugins/hyprexpo.conf

exec-once = gnome-keyring-daemon --start --components=pkcs11,secrets,ssh
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = swaync
exec-once = swww-daemon
exec-once = waypaper --restore
exec-once = swayosd-server
exec-once = ~/.local/bin/waybar-theme --init
exec-once = hypridle
exec-once = hyprpm reload -n
