input {
    kb_layout = us
    kb_options = caps:super
}

$terminal = kitty
$mod = SUPER

bind = $mod, Return, exec, $terminal
bind = $mod, Q, killactive
bind = $mod, SHIFT, R, exec, hyprctl reload

bind = $mod, A, workspace, -1
bind = $mod, S, workspace, +1
