-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        inactive_opacity = 0.8,
        rounding = 8,
    },
    general = {
        border_size = 3,
        gaps_in = 2,
        gaps_out = 10,
        resize_on_border = true,
    },
    input = {
        natural_scroll = true,
        sensitivity = -0.3,
    },
})
