bind = $mod, Return, exec, $terminal
bind = $mod shift, L, exec, hyprlock
bind = $mod alt, X, exec, $power-menu

bind = $mod, B, exec, $browser
bind = $mod alt, B, exec, $bluetooth-manager

bind = $mod, Q, killactive
bind = $mod alt, R, exec, hyprctl reload

bind = $mod, SPACE, exec, $menu

bind = $mod, A, workspace, -1
bind = $mod, S, workspace, +1
bind = $mod, D, movetoworkspace, -1
bind = $mod, F, movetoworkspace, +1

bind = $mod, H, movefocus, l
bind = $mod, J, movefocus, d
bind = $mod, K, movefocus, u
bind = $mod, L, movefocus, r

bind = $mod alt, H, movewindow, l
bind = $mod alt, J, movewindow, d
bind = $mod alt, K, movewindow, u
bind = $mod alt, L, movewindow, r

binde = , XF86AudioRaiseVolume, exec, swayosd-client --output-volume raise
binde = , XF86AudioLowerVolume, exec, swayosd-client --output-volume lower
bind = , XF86AudioMute, exec, swayosd-client --output-volume mute-toggle

bind = , XF86AudioPlay, exec, swayosd-client --playerctl play-pause
bind = , XF86AudioPause, exec, swayosd-client --playerctl play-pause
bind = , XF86AudioNext, exec, swayosd-client --playerctl next
bind = , XF86AudioPrev, exec, swayosd-client --playerctl prev

binde = , XF86MonBrightnessUp, exec, swayosd-client --brightness raise
binde = , XF86MonBrightnessDown, exec, swayosd-client --brightness lower
