bind = $mod, Return, exec, $terminal
bind = $mod alt, X, exec, $power-menu
bind = $mod shift, S, exec, $screenshot
bind = , print, exec, $screenshot
bind = $mod alt, comma, exec, ~/.local/bin/kb-layout --next
bind = $mod, R, hyprexpo:expo, toggle
bind = $mod alt, Backspace, exec, ~/.local/bin/hyprland-cheatsheet
bind = $mod, M, layoutmsg, swapwithmaster master

bind = $mod, B, exec, $browser
bind = $mod alt, B, exec, $bluetooth-manager
bind = $mod shift, B, exec, ~/.local/bin/waybar-theme --select-wofi

bind = $mod, Q, killactive
bind = $mod alt, R, exec, kitty -e sh -c 'hyprctl reload; read'
bind = $mod, V, togglefloating

bind = $mod, SPACE, exec, $menu

binde = $mod, A, workspace, -1
binde = $mod, S, workspace, +1
binde = $mod, D, movetoworkspace, -1
binde = $mod, F, movetoworkspace, +1

gesture = 3, horizontal, workspace

bind = $mod, H, movefocus, l
bind = $mod, J, movefocus, d
bind = $mod, K, movefocus, u
bind = $mod, L, movefocus, r

bind = $mod alt, H, movewindow, l
bind = $mod alt, J, movewindow, d
bind = $mod alt, K, movewindow, u
bind = $mod alt, L, movewindow, r

binde = $mod shift, H, resizeactive, -10 0
binde = $mod shift, J, resizeactive, 0 -10
binde = $mod shift, K, resizeactive, 0 10
binde = $mod shift, L, resizeactive, 10 0

bindm = $mod, mouse:272, movewindow

binde = , XF86AudioRaiseVolume, exec, swayosd-client --output-volume raise
binde = , XF86AudioLowerVolume, exec, swayosd-client --output-volume lower
bind = , XF86AudioMute, exec, swayosd-client --output-volume mute-toggle

bind = , XF86AudioPlay, exec, swayosd-client --playerctl play-pause
bind = , XF86AudioPause, exec, swayosd-client --playerctl play-pause
bind = , XF86AudioNext, exec, swayosd-client --playerctl next
bind = , XF86AudioPrev, exec, swayosd-client --playerctl prev

binde = , XF86MonBrightnessUp, exec, swayosd-client --brightness raise
binde = , XF86MonBrightnessDown, exec, swayosd-client --brightness lower

bindl = , switch:on:Lid Switch, exec, hyprctl dispatch dpms off
bindl = , switch:off:Lid Switch, exec, hyprctl dispatch dpms on
