bind = $mod, Return, exec, $terminal

bind = $mod, B, exec, $browser
bind = $mod alt, B, exec, $bluetooth-manager

bind = $mod, Q, killactive
bind = $mod alt, R, exec, hyprctl reload

bind = $mod, SPACE, exec, $menu

bind = $mod, A, workspace, -1
bind = $mod, S, workspace, +1
bind = $mod, D, movetoworkspace, -1
bind = $mod, F, movetoworkspace, +1

bind = $mod, H, movefocus, l
bind = $mod, J, movefocus, d
bind = $mod, K, movefocus, u
bind = $mod, L, movefocus, r

bind = $mod alt, H, movewindow, l
bind = $mod alt, J, movewindow, d
bind = $mod alt, K, movewindow, u
bind = $mod alt, L, movewindow, r