windowrule {
    name = "Picture In Picture"
    match:title = ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
    
    float = on
    keep_aspect_ratio = on
    pin = on
    move = (monitor_w*0.73) (monitor_h*0.72)
    size = (monitor_w*0.25) (monitor_h*0.25)
}

windowrule {
    name = "Picture In Picture (TWITCH)"
    match:initial_class = "microsoft-edge"
    match:initial_title = "Untitled - Personal - Microsoft Edge"
    match:title = "Twitch - Personal - Microsoft Edge"

    float = on
    keep_aspect_ratio = on
    pin = on
    move = (monitor_w*0.73) (monitor_h*0.72)
    size = (monitor_w*0.25) (monitor_h*0.25)
}

windowrule {
    name = "Microsoft Edge"
    match:class = ^(microsoft-edge)$
    match:title = ^()$

    no_initial_focus = on
}

windowrule {
    name = xwayland-video-bridge-fixes
    match:class = xwaylandvideobridge

    no_initial_focus = true
    no_focus = true
    no_anim = true
    no_blur = true
    max_size = 1 1
    opacity = 0.0
}

layerrule {
    name = waybar
    match:namespace = waybar
    no_anim = on
}